spring.application.name=spring-bot

bot.token=8587759116:AAG3Q2Oy_jVQSPmKRe9g5ixxFzrNjjzj0KM

spring.datasource.url=jdbc:postgresql://localhost:5432/telegram-bot
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.option.model=arcee-ai/trinity-large-preview:free