spring.application.name=spring-bot

bot.token=

spring.datasource.url=jdbc:postgresql://localhost:5432/telegram-bot
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.ai.openai.api-key=
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.option.model=arcee-ai/trinity-large-preview:free
